DROP SCHEMA TrurApp;
CREATE SCHEMA TrurApp;

DROP TABLE TrurApp.Point;
DROP TABLE TrurApp.Transport;
DROP TABLE TrurApp.TransportType;

CREATE TABLE TrurApp.TransportType (
	ID INTEGER NOT NULL,
	Name VARCHAR(64) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE TrurApp.Transport (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	Name VARCHAR(8) NOT NULL,
	TransportTypeId INTEGER,
	PRIMARY KEY (ID),
	CONSTRAINT TT_FK FOREIGN KEY (TransportTypeId) REFERENCES TrurApp.TransportType (ID)
);

CREATE TABLE TrurApp.Point (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	TransportId INTEGER,
	Position Integer,
	Lat DOUBLE,
	Lng DOUBLE,
	PRIMARY KEY (ID),
	CONSTRAINT T_FK FOREIGN KEY (TransportId) REFERENCES TrurApp.Transport (ID)
);
